Product=input("Product bought: ")
Quantity=int(input("How much do you need? "))
Price=input("Enter the price :")
Bill=Quantity*float(Price)
print()
print()
print("------------")
print("Your Invoice:")
print("1. Product: ",Product)
print("2. Quantity: ",Quantity)
print("3. Price: ",Price)
print("Your bill comes to: £",Bill)